CREATE DATABASE adannupc_cardiograma;

USE adannupc_cardiograma;

CREATE TABLE datos(
	id_datos INT NOT NULL AUTO_INCREMENT,
	one INT NOT NULL,
	two INT NOT NULL,
	three INT NOT NULL,
	ip VARCHAR(50) NOT NULL, 
	fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id_datos)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;